# Clock signal
set_property PACKAGE_PIN W5 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports sys_clock]

# Buttons
set_property PACKAGE_PIN U18 [get_ports rst_0]
set_property IOSTANDARD LVCMOS33 [get_ports rst_0]

set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports {Pixel_sel_0[0]}]
set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports {Pixel_sel_0[1]}]

# VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vgaRed_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed_0[0]}]
set_property PACKAGE_PIN H19 [get_ports {vgaRed_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed_0[1]}]
set_property PACKAGE_PIN J19 [get_ports {vgaRed_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed_0[2]}]
set_property PACKAGE_PIN N19 [get_ports {vgaRed_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed_0[3]}]
set_property PACKAGE_PIN N18 [get_ports {vgaBlue_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue_0[0]}]
set_property PACKAGE_PIN L18 [get_ports {vgaBlue_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue_0[1]}]
set_property PACKAGE_PIN K18 [get_ports {vgaBlue_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue_0[2]}]
set_property PACKAGE_PIN J18 [get_ports {vgaBlue_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue_0[3]}]
set_property PACKAGE_PIN J17 [get_ports {vgaGreen_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen_0[0]}]
set_property PACKAGE_PIN H17 [get_ports {vgaGreen_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen_0[1]}]
set_property PACKAGE_PIN G17 [get_ports {vgaGreen_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen_0[2]}]
set_property PACKAGE_PIN D17 [get_ports {vgaGreen_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen_0[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync_0]
set_property IOSTANDARD LVCMOS33 [get_ports hsync_0]
set_property PACKAGE_PIN R19 [get_ports vsync_0]
set_property IOSTANDARD LVCMOS33 [get_ports vsync_0]

# Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]